import type { DatabaseConnection } from '../initializeDatabase';

export const DEFAULT_SEED_EXERCISES = [
  { id: 'bench-press', name: 'Bench Press', muscleGroup: 'Chest', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'incline-bench-press', name: 'Incline Bench Press', muscleGroup: 'Chest', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'decline-bench-press', name: 'Decline Bench Press', muscleGroup: 'Chest', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'close-grip-bench-press', name: 'Close Grip Bench Press', muscleGroup: 'Chest', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'wide-grip-bench-press', name: 'Wide Grip Bench Press', muscleGroup: 'Chest', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'guillotine-press', name: 'Guillotine Press', muscleGroup: 'Chest', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'floor-press', name: 'Floor Press', muscleGroup: 'Chest', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-bench-press', name: 'Dumbbell Bench Press', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'decline-dumbbell-press', name: 'Decline Dumbbell Press', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-floor-press', name: 'Dumbbell Floor Press', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-fly', name: 'Dumbbell Fly', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'incline-dumbbell-fly', name: 'Incline Dumbbell Fly', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'decline-dumbbell-fly', name: 'Decline Dumbbell Fly', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-pullover', name: 'Dumbbell Pullover', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'squeeze-press', name: 'Squeeze Press', muscleGroup: 'Chest', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-fly', name: 'Cable Fly', muscleGroup: 'Chest', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'low-to-high-cable-fly', name: 'Low to High Cable Fly', muscleGroup: 'Chest', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'high-to-low-cable-fly', name: 'High to Low Cable Fly', muscleGroup: 'Chest', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'standing-cable-chest-press', name: 'Standing Cable Chest Press', muscleGroup: 'Chest', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-cable-fly', name: 'Single Arm Cable Fly', muscleGroup: 'Chest', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-cable-chest-press', name: 'Single Arm Cable Chest Press', muscleGroup: 'Chest', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'chest-press', name: 'Chest Press', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'incline-chest-press', name: 'Incline Chest Press', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'decline-chest-press', name: 'Decline Chest Press', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pec-deck', name: 'Pec Deck', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'plate-loaded-chest-press', name: 'Plate Loaded Chest Press', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-bench-press', name: 'Smith Machine Bench Press', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-incline-press', name: 'Smith Machine Incline Press', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-decline-press', name: 'Smith Machine Decline Press', muscleGroup: 'Chest', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'push-up', name: 'Push Up', muscleGroup: 'Chest', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'wide-push-up', name: 'Wide Push Up', muscleGroup: 'Chest', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'diamond-push-up', name: 'Diamond Push Up', muscleGroup: 'Chest', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'decline-push-up', name: 'Decline Push Up', muscleGroup: 'Chest', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'incline-push-up', name: 'Incline Push Up', muscleGroup: 'Chest', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'chest-dip', name: 'Chest Dip', muscleGroup: 'Chest', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-row', name: 'Barbell Row', muscleGroup: 'Back', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pendlay-row', name: 'Pendlay Row', muscleGroup: 'Back', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'underhand-barbell-row', name: 'Underhand Barbell Row', muscleGroup: 'Back', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'deadlift', name: 'Deadlift', muscleGroup: 'Back', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'rack-pull', name: 'Rack Pull', muscleGroup: 'Back', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'landmine-row', name: 'Landmine Row', muscleGroup: 'Back', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'meadows-row', name: 'Meadows Row', muscleGroup: 'Back', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'one-arm-dumbbell-row', name: 'One Arm Dumbbell Row', muscleGroup: 'Back', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-row', name: 'Dumbbell Row', muscleGroup: 'Back', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'chest-supported-dumbbell-row', name: 'Chest Supported Dumbbell Row', muscleGroup: 'Back', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'renegade-row', name: 'Renegade Row', muscleGroup: 'Back', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'wide-grip-lat-pulldown', name: 'Wide Grip Lat Pulldown', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'close-grip-lat-pulldown', name: 'Close Grip Lat Pulldown', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'neutral-grip-lat-pulldown', name: 'Neutral Grip Lat Pulldown', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'underhand-lat-pulldown', name: 'Underhand Lat Pulldown', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-lat-pulldown', name: 'Single Arm Lat Pulldown', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'straight-arm-pulldown', name: 'Straight Arm Pulldown', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'seated-cable-row', name: 'Seated Cable Row', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'wide-grip-cable-row', name: 'Wide Grip Cable Row', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'close-grip-cable-row', name: 'Close Grip Cable Row', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-cable-row', name: 'Single Arm Cable Row', muscleGroup: 'Back', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'machine-row', name: 'Machine Row', muscleGroup: 'Back', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'chest-supported-machine-row', name: 'Chest Supported Machine Row', muscleGroup: 'Back', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'high-row-machine', name: 'High Row Machine', muscleGroup: 'Back', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'low-row-machine', name: 'Low Row Machine', muscleGroup: 'Back', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'plate-loaded-row', name: 'Plate Loaded Row', muscleGroup: 'Back', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'machine-pullover', name: 'Machine Pullover', muscleGroup: 'Back', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'assisted-pull-up', name: 'Assisted Pull Up', muscleGroup: 'Back', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pull-up', name: 'Pull Up', muscleGroup: 'Back', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'chin-up', name: 'Chin Up', muscleGroup: 'Back', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'neutral-grip-pull-up', name: 'Neutral Grip Pull Up', muscleGroup: 'Back', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'wide-grip-pull-up', name: 'Wide Grip Pull Up', muscleGroup: 'Back', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'inverted-row', name: 'Inverted Row', muscleGroup: 'Back', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'back-squat', name: 'Back Squat', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'front-squat', name: 'Front Squat', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'zercher-squat', name: 'Zercher Squat', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'box-squat', name: 'Box Squat', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pause-squat', name: 'Pause Squat', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-lunge', name: 'Barbell Lunge', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'walking-barbell-lunge', name: 'Walking Barbell Lunge', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'stiff-leg-deadlift', name: 'Stiff Leg Deadlift', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'sumo-deadlift', name: 'Sumo Deadlift', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'good-morning', name: 'Good Morning', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-hip-thrust', name: 'Barbell Hip Thrust', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-glute-bridge', name: 'Barbell Glute Bridge', muscleGroup: 'Legs', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-squat', name: 'Dumbbell Squat', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'goblet-squat', name: 'Goblet Squat', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-bulgarian-split-squat', name: 'Dumbbell Bulgarian Split Squat', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-walking-lunge', name: 'Dumbbell Walking Lunge', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-reverse-lunge', name: 'Dumbbell Reverse Lunge', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-step-up', name: 'Dumbbell Step Up', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-romanian-deadlift', name: 'Dumbbell Romanian Deadlift', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-stiff-leg-deadlift', name: 'Dumbbell Stiff Leg Deadlift', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-hip-thrust', name: 'Dumbbell Hip Thrust', muscleGroup: 'Legs', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'leg-press', name: 'Leg Press', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-leg-press', name: 'Single Leg Press', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'hack-squat', name: 'Hack Squat', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pendulum-squat', name: 'Pendulum Squat', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'leg-extension', name: 'Leg Extension', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-leg-extension', name: 'Single Leg Extension', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'belt-squat', name: 'Belt Squat', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'lying-leg-curl', name: 'Lying Leg Curl', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'seated-leg-curl', name: 'Seated Leg Curl', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'standing-leg-curl', name: 'Standing Leg Curl', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-leg-curl', name: 'Single Leg Curl', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'hip-abduction', name: 'Hip Abduction', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'hip-adduction', name: 'Hip Adduction', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'glute-kickback-machine', name: 'Glute Kickback Machine', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'standing-calf-raise', name: 'Standing Calf Raise', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'seated-calf-raise', name: 'Seated Calf Raise', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'leg-press-calf-raise', name: 'Leg Press Calf Raise', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-leg-calf-raise', name: 'Single Leg Calf Raise', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'donkey-calf-raise', name: 'Donkey Calf Raise', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-squat', name: 'Smith Machine Squat', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-front-squat', name: 'Smith Machine Front Squat', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-bulgarian-split-squat', name: 'Smith Machine Bulgarian Split Squat', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-lunge', name: 'Smith Machine Lunge', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-calf-raise', name: 'Smith Machine Calf Raise', muscleGroup: 'Legs', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-pull-through', name: 'Cable Pull Through', muscleGroup: 'Legs', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-glute-kickback', name: 'Cable Glute Kickback', muscleGroup: 'Legs', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-hip-abduction', name: 'Cable Hip Abduction', muscleGroup: 'Legs', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-hip-adduction', name: 'Cable Hip Adduction', muscleGroup: 'Legs', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'bodyweight-squat', name: 'Bodyweight Squat', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'walking-lunge', name: 'Walking Lunge', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'reverse-lunge', name: 'Reverse Lunge', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'step-up', name: 'Step Up', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pistol-squat', name: 'Pistol Squat', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'wall-sit', name: 'Wall Sit', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'glute-bridge', name: 'Glute Bridge', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-leg-glute-bridge', name: 'Single Leg Glute Bridge', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'nordic-hamstring-curl', name: 'Nordic Hamstring Curl', muscleGroup: 'Legs', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'overhead-press', name: 'Overhead Press', muscleGroup: 'Shoulders', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'seated-barbell-shoulder-press', name: 'Seated Barbell Shoulder Press', muscleGroup: 'Shoulders', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'push-press', name: 'Push Press', muscleGroup: 'Shoulders', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'behind-the-neck-press', name: 'Behind the Neck Press', muscleGroup: 'Shoulders', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-front-raise', name: 'Barbell Front Raise', muscleGroup: 'Shoulders', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-upright-row', name: 'Barbell Upright Row', muscleGroup: 'Shoulders', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-shoulder-press', name: 'Dumbbell Shoulder Press', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'seated-dumbbell-shoulder-press', name: 'Seated Dumbbell Shoulder Press', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'arnold-press', name: 'Arnold Press', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-lateral-raise', name: 'Dumbbell Lateral Raise', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'seated-lateral-raise', name: 'Seated Lateral Raise', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'leaning-lateral-raise', name: 'Leaning Lateral Raise', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-front-raise', name: 'Dumbbell Front Raise', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'rear-delt-fly', name: 'Rear Delt Fly', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'chest-supported-rear-delt-fly', name: 'Chest Supported Rear Delt Fly', muscleGroup: 'Shoulders', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-lateral-raise', name: 'Cable Lateral Raise', muscleGroup: 'Shoulders', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-cable-lateral-raise', name: 'Single Arm Cable Lateral Raise', muscleGroup: 'Shoulders', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-front-raise', name: 'Cable Front Raise', muscleGroup: 'Shoulders', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-rear-delt-fly', name: 'Cable Rear Delt Fly', muscleGroup: 'Shoulders', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'face-pull', name: 'Face Pull', muscleGroup: 'Shoulders', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-upright-row', name: 'Cable Upright Row', muscleGroup: 'Shoulders', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'machine-shoulder-press', name: 'Machine Shoulder Press', muscleGroup: 'Shoulders', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'machine-lateral-raise', name: 'Machine Lateral Raise', muscleGroup: 'Shoulders', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'rear-delt-machine', name: 'Rear Delt Machine', muscleGroup: 'Shoulders', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'reverse-pec-deck', name: 'Reverse Pec Deck', muscleGroup: 'Shoulders', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-shoulder-press', name: 'Smith Machine Shoulder Press', muscleGroup: 'Shoulders', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'smith-machine-upright-row', name: 'Smith Machine Upright Row', muscleGroup: 'Shoulders', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pike-push-up', name: 'Pike Push Up', muscleGroup: 'Shoulders', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'handstand-push-up', name: 'Handstand Push Up', muscleGroup: 'Shoulders', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-curl', name: 'Barbell Curl', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'ez-bar-curl', name: 'EZ Bar Curl', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'wide-grip-barbell-curl', name: 'Wide Grip Barbell Curl', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'reverse-barbell-curl', name: 'Reverse Barbell Curl', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'drag-curl', name: 'Drag Curl', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'skull-crusher', name: 'Skull Crusher', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'ez-bar-skull-crusher', name: 'EZ Bar Skull Crusher', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'jm-press', name: 'JM Press', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-wrist-curl', name: 'Barbell Wrist Curl', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'barbell-reverse-wrist-curl', name: 'Barbell Reverse Wrist Curl', muscleGroup: 'Arms', category: 'Barbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-curl', name: 'Dumbbell Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'alternating-dumbbell-curl', name: 'Alternating Dumbbell Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cross-body-hammer-curl', name: 'Cross Body Hammer Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'incline-dumbbell-curl', name: 'Incline Dumbbell Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'concentration-curl', name: 'Concentration Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'spider-curl', name: 'Spider Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'zottman-curl', name: 'Zottman Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'preacher-dumbbell-curl', name: 'Preacher Dumbbell Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-skull-crusher', name: 'Dumbbell Skull Crusher', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-overhead-triceps-extension', name: 'Dumbbell Overhead Triceps Extension', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-dumbbell-extension', name: 'Single Arm Dumbbell Extension', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-kickback', name: 'Dumbbell Kickback', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-wrist-curl', name: 'Dumbbell Wrist Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dumbbell-reverse-wrist-curl', name: 'Dumbbell Reverse Wrist Curl', muscleGroup: 'Arms', category: 'Dumbbell', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'farmer-walk', name: 'Farmer Walk', muscleGroup: 'Arms', category: 'Other', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-curl', name: 'Cable Curl', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'rope-hammer-curl', name: 'Rope Hammer Curl', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-cable-curl', name: 'Single Arm Cable Curl', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'high-cable-curl', name: 'High Cable Curl', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'bayesian-cable-curl', name: 'Bayesian Cable Curl', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'triceps-pushdown', name: 'Triceps Pushdown', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'rope-triceps-pushdown', name: 'Rope Triceps Pushdown', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'straight-bar-pushdown', name: 'Straight Bar Pushdown', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'reverse-grip-pushdown', name: 'Reverse Grip Pushdown', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'overhead-rope-extension', name: 'Overhead Rope Extension', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-triceps-pushdown', name: 'Single Arm Triceps Pushdown', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'single-arm-overhead-extension', name: 'Single Arm Overhead Extension', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-kickback', name: 'Cable Kickback', muscleGroup: 'Arms', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'preacher-curl', name: 'Preacher Curl', muscleGroup: 'Arms', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'machine-biceps-curl', name: 'Machine Biceps Curl', muscleGroup: 'Arms', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'machine-triceps-extension', name: 'Machine Triceps Extension', muscleGroup: 'Arms', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'assisted-dip', name: 'Assisted Dip', muscleGroup: 'Arms', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'triceps-dip', name: 'Triceps Dip', muscleGroup: 'Arms', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'bench-dip', name: 'Bench Dip', muscleGroup: 'Arms', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'plank', name: 'Plank', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'side-plank', name: 'Side Plank', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'crunch', name: 'Crunch', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'sit-up', name: 'Sit Up', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'bicycle-crunch', name: 'Bicycle Crunch', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'reverse-crunch', name: 'Reverse Crunch', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'leg-raise', name: 'Leg Raise', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'lying-leg-raise', name: 'Lying Leg Raise', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'hanging-knee-raise', name: 'Hanging Knee Raise', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'mountain-climber', name: 'Mountain Climber', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'dead-bug', name: 'Dead Bug', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'bird-dog', name: 'Bird Dog', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'hollow-body-hold', name: 'Hollow Body Hold', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'v-up', name: 'V Up', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'toe-touch', name: 'Toe Touch', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'russian-twist', name: 'Russian Twist', muscleGroup: 'Core', category: 'Bodyweight', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroup: 'Core', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'kneeling-cable-crunch', name: 'Kneeling Cable Crunch', muscleGroup: 'Core', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-wood-chop', name: 'Cable Wood Chop', muscleGroup: 'Core', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'cable-rotation', name: 'Cable Rotation', muscleGroup: 'Core', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'pallof-press', name: 'Pallof Press', muscleGroup: 'Core', category: 'Cable', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'abdominal-crunch-machine', name: 'Abdominal Crunch Machine', muscleGroup: 'Core', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'rotary-torso-machine', name: 'Rotary Torso Machine', muscleGroup: 'Core', category: 'Machine', isCustom: false, createdAt: 0, updatedAt: 0 },
  { id: 'ab-wheel-rollout', name: 'Ab Wheel Rollout', muscleGroup: 'Core', category: 'Other', isCustom: false, createdAt: 0, updatedAt: 0 },
] as const;

export async function seedExercises(database: DatabaseConnection): Promise<void> {
  for (const item of DEFAULT_SEED_EXERCISES) {
    await (database as any).runAsync?.(
      `INSERT OR IGNORE INTO exercises (id, name, muscle_group, category, is_custom, created_at, updated_at)
       VALUES (?, ?, ?, ?, 0, ?, ?);`,
      [item.id, item.name, item.muscleGroup, item.category, item.createdAt, item.updatedAt],
    ) ?? (database as any).execAsync?.(
      `INSERT OR IGNORE INTO exercises (id, name, muscle_group, category, is_custom, created_at, updated_at)
       VALUES ('${item.id}', '${item.name}', '${item.muscleGroup}', '${item.category}', 0, ${item.createdAt}, ${item.updatedAt});`
    );
  }
}
